### ISSUE TITLE
before commands not executing

### ISSUE THREAD

**Issue by raid5** [achiurizo/terminitor#2]
Any `before` commands I have specified, like a `cd` into a directory, don't seem to be executed anymore. I'm basically taking an example that works with `terminitor` and attempting to get it running under `consular`.

**Comment by achiurizo** [comment]
which core are you using?

**Comment by achiurizo** [comment]
If you are using `consular-osx`, i've fixed it here: https://github.com/achiu/consular-osx/commit/8f993563e43acc88ac059ab9d00369ceb1404c21. Let me know if this works for you. If not feel free to reopen the ticket.

**Comment by raid5** [comment]
Works like a charm. Thanks!
