### ISSUE TITLE
Getting error: No valid core was found!. Exiting... 

### ISSUE THREAD

**Issue by epinault** [achiurizo/terminitor#4]
Followed the README but still cannot get it to work. I am using Ruby 1.9.2 P290,(Via RVM), consular 1.0.1 and consular-gnome-terminal 0.1.1

I did after editing my .consularc

consular init
consular edit test 
consular start test

This is my .consularc

<pre>
# You can require your additional core gems here.
# require 'some_core_gem'
require 'consular/gnome-terminal'

# You can set specific Consular configurations
# here.
Consular.configure do |c|
  # c.global_path    = '~/.config/consular'
  # c.default_editor = 'vim'
end
</pre>

what am I missing?

Thanks

**Comment by achiurizo** [comment]
what OS are you using? I think this might have to do with the `valid_system?` specification defined by the core: https://github.com/jc00ke/consular-gnome-terminal/blob/master/lib/consular/gnome-terminal.rb#L20. Maybe you are missing `xdotool`?

**Comment by epinault** [comment]
I did not install xdotool . Must have miss that somewhere.. Did not see it in the README as a step to install nor how :(

**Comment by epinault** [comment]
Installing it worked! thanks!

**Comment by achiurizo** [comment]
yeah `xdotool` is specific for consular-gnome-terminal. It's a actually a fork off of consular-terminator. In the README it shows that it uses it. perhaps it could be more clearer. closing ticket.

**Comment by RKushnir** [comment]
Hi. I can't find anything about "xdotool" in the Readme. You're giving just these 2 commands:

```
gem install consular
consular init
```

It would be better not to require everyone to look in the issues list.

**Comment by RKushnir** [comment]
Installed `consular-gnome-terminal` gem and `xdotool` and still the same error. I'm using Ubuntu 10.04.

**Comment by achiurizo** [comment]
Did you require the gem in `.consularc` ? I've made the [README](https://github.com/achiu/consular/blob/master/README.md) much clearer so hopefully this makes it more clear.

**Comment by RKushnir** [comment]
In case someone else faces this issue, here's the sequence for ubuntu:

```
gem install consular
consular init
apt-get install xdotool
gem install consular-gnome-terminal
# add require 'consular/gnome-terminal' to ~/.consularc
```
